services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    volumes:
      - ./data/tessdata:/usr/share/tessdata  # OCR language files
      - ./data/configs:/configs              # Settings & database
      - ./data/logs:/logs                    # Application logs
      - ./data/pipeline:/pipeline            # Automation configs
    environment:
      - SECURITY_ENABLELOGIN=true
      - LANGS=en_GB
    restart: unless-stopped

networks:
  default:
    external: true
    name: nginx-proxy-manager