services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${PUID:-950}
      - PGID=${PGID:-950}
      - TZ=${TZ:-Etc/UTC}
      - LOG_CONFS=true
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules #optional
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  gateway-nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: gateway-nginx
    network_mode: service:wireguard
    environment:
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/usr/bin/check-health"]
      interval: 10s
      timeout: 3s

networks:
  default:
    external: true
    name: nginx-proxy-manager