services:
  beszel:
    image: henrygd/beszel
    container_name: beszel
    networks:
      - nginx-proxy-manager
    volumes:
      - ./beszel_data:/beszel_data
    restart: unless-stopped

  beszel-agent:
    image: henrygd/beszel-agent-nvidia
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./beszel_agent_data:/var/lib/beszel-agent
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      - /mnt/NVMe/media/.beszel:/extra-filesystems/sda1__Media:ro
    env_file:
      - .env
    environment:
      - LISTEN=45876
      - KEY=${KEY}
      - TOKEN=${TOKEN}
      - HUB_URL=https://beszel.home.gerardgascon.com
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - utility

networks:
  nginx-proxy-manager:
    external: true