server:
  proxied: true

branding:
  hide-footer: true

pages:
  - name: Startpage
    width: slim
    center-vertically: true
    hide-desktop-navigation: true
    show-mobile-header: false
    columns:
      - size: full
        widgets:
          - type: search
            search-engine: duckduckgo
            bangs:
              - title: YouTube
                shortcut: "!yt"
                url: https://www.youtube.com/results?search_query={QUERY}

          - type: docker-containers
            title: Services
            hide-by-default: true
            containers:
              nginx-proxy-manager:
                name: Nginx Proxy Manager
                description: Reverse Proxy
                url: https://nginx.pi.gerardgascon.com
                icon: si:nginxproxymanager
                hide: false
              pihole:
                name: Pi-hole
                description: Ad-blocking
                url: https://pihole.pi.gerardgascon.com/admin
                icon: si:pihole
                hide: false
              tailscale:
                name: Tailscale
                description: Zero Trust Access
                icon: si:tailscale
                hide: false
              upsnap:
                name: UpSnap
                description: Wake on LAN
                url: https://upsnap.pi.gerardgascon.com
                hide: false
              uptime-kuma:
                name: Uptime Kuma
                description: Service Monitoring Tool
                url: https://uptime.pi.gerardgascon.com
                icon: si:uptimekuma
                hide: false
              docker-deploy-notifier:
                name: Docker Deploy Notifier
                description: Discord Notification for Deployment
                hide: false